### ISSUE TITLE
[Home] - Portal de vagas

### ISSUE THREAD

**Issue by caiquefonseca** [SouJunior/products#355]
Item criado para realização de testes relacionados à [US#224](https://github.com/SouJunior/products/issues/224)

**Comment by caiquefonseca** [comment]
- [ ] Quando o usuário clicar na logomarca da SouJunior que ficará na parte superior da lateral esquerda do header, ele deve ser direcionado para o topo da página do Home do portal de vagas;
- [ ] Quando o usuário clicar no botão "Candidate-se" indicado na parte superior da direita do header, ele deve ser direcionado para a https://github.com/SouJunior/products/issues/110;
- [ ] Quando o usuário clicar no botão "Login" indicado na parte superior da lateral direita do header, após o no botão de cadatro, ele deve ser direcionado para a área de https://github.com/SouJunior/products/issues/29;
- [ ] No header acima do campo de buscar vaga deve conter o pitch "Um Portal de Vagas exclusivo para o profissional Junior";
- [ ] No header abaixo do pitch do header deve conter o campo para buscar por vagas com 796 pixels, com uma lupa e a frase "Digite cargo" em máscara e quando o usuário digitar um cargo e clicar no botão "Buscar Vaga", ele deve ser direcionado para o https://github.com/SouJunior/vagas-backend/issues/87;
- [ ] No header abaixo do campo de busca de vagas deve conter o indicador da quantidade de vagas disponível no portal de vagas, independentemente do tipo de vaga, com a frase "Mais de xxx vagas disponíveis para juninhos". O total indicado (xxx) deve ser o menor número múltiplo de 10, exemplo: Se o total de vagas cadastradas no portal de vagas da SouJunior for 215, deve ser indicado: "Mais de 210 vagas disponíveis para juninho";
- [ ] Quando o usuário fizer o scroll da página a parte superior do header deve ficar fixa, o campo para pesquisar vagas reduzirá de tamanho para 589 pixels e ficará entre a logo marca da SouJunior e o botão "Cadastre-se", criando um NAV Bar para utilização a qualquer momento;
- [ ] Deve haver o título fixo "Já sabe por onde começar?" para o carrossel com algumas áreas de tecnologia para usuário conhecer mais;
- [ ] As áreas de atuação devem ficar em carrossel e quando o usuário clicar em alguma delas, deve abrir um pop-up de cada uma das áreas de atuação. Os textos devem ser específicos de cada área, indicado no arquivo: https://docs.google.com/document/d/1D-TtoBvVNn5Tnphbu7fswk4ywSizExfG/edit?usp=share_link&ouid=115624203904480055006&rtpof=true&sd=true , com os links das fontes dos textos;
- [ ] Deve ter o banner indicando um teste vocacional e quando o usuário clicar neste deve ser direcionado para uma nova aba do site para que realize o teste: https://especiais.g1.globo.com/educacao/guia-de-carreiras/teste-vocacional/ ;
- [ ] Deve haver um título indicando a quebra de sessão "Seja o Júnior que as empresas desejam" acima dos cards do portal de mentoria, site soujunior e youtube
- [ ] Quando o usuário clicar em "Portal de Mentoria", deve ser direcionado para o site do [Portal de Mentoria](http://mentores.soujunior.tech/);
- [ ] Quando o usuário clicar em "Portal SouJunior" deve ser direcionado para o [Site da SouJunior](http://www.soujunior.tech/) ;
- [ ] Quando o susuário clicar em "Fique Ligado na SouJunior" deve ser direcionado para o [Youtube da SouJunior](https://www.youtube.com/@soujuniortech);
- [ ] Deve haver um título indicando a quebra de sessão "Vamos juntos nessa jornada" abaixo dos cards do portal de mentoria, site soujunior e youtube;
- [ ] Quando o usuário clicar na imagem ou título do arquivo "Se destaque no Linkedin" que está abaixo do título "Vamos juntos nessa jornada" deve abrir uma nova janela com o texto do arquivo 01- Se destaque no Linkedin: https://docs.google.com/document/d/1I5uqGr3XLS15QKSV5pSLBEcek1oGc4qX/edit?usp=share_link&ouid=115624203904480055006&rtpof=true&sd=true e se o usuário clicar fora do pop-up ou no "X" no canto superior direito da janela deve retornar a página home;
- [ ] Quando o usuário clicar na imagem ou título do arquivo "Como construir um curriculo junior" que está abaixo do título "Vamos juntos nessa jornada" deve abrir uma nova janela com o texto do arquivo 02- Como preparar um curriculo Junior: https://docs.google.com/document/d/1qDm_4Rgi0cgeHvAgMZ446wzUOnRfJSLu/edit?usp=share_link&ouid=115624203904480055006&rtpof=true&sd=true e se o usuário clicar fora do pop-up ou no "X" no canto superior direito da janela deve retornar a página home;
- [ ] Quando o usuário clicar na imagem ou título do arquivo "Se prepare para processos seletivos" que está abaixo do card "Se destaque no Linkedin" deve abrir uma nova janela com o texto do arquivo 03- Se prepare para processos seletivos: https://docs.google.com/document/d/1mJ42ZFhEjI7dSuWSpnGsumJNpp0z0VHB/edit?usp=share_link&ouid=115624203904480055006&rtpof=true&sd=true e se o usuário clicar fora do pop-up ou no "X" no canto superior direito da janela deve retornar a página home;
- [ ] Quando o usuário clicar na imagem ou título do arquivo "Palavras-chaves para área tech" que está abaixo do card "Como construir um curriculo junior" deve abrir uma nova janela com o texto do arquivo 04- Palavas-chaves na área tech: https://docs.google.com/document/d/15_kfown182Afc9sphlozLBW6HT7hGLkw/edit?usp=share_link&ouid=115624203904480055006&rtpof=true&sd=true e se o usuário clicar fora do pop-up ou no "X" no canto superior direito da janela deve retornar a página home;
- [ ] Deve haver um banner clicável indicando que o usuário poderá baixar o app do portal de vagas da SouJunior;
- [ ] Se o usuário estiver navegando por um dispositivo android e clicar no banner ele deve ser direcionado para a página do google play para baixar o aplicativo;
- [ ] Se o usuário estiver navegando por um dispositivo IOS e clicar no banner ele deve ser direcionado para a página do google play, se e somente se, ele tiver conta no Google aparecerá os dispositivos que ele poderá baixar o app do portal de vagas da SouJunior;
- [ ] Se o usuário estiver navegando por um computador desktop ou laptop e clicar no banner ele deve ser direcionado para a página do google play, se e somente se, ele tiver conta no Google aparecerá os dispositivos que ele poderá baixar o app do portal de vagas da SouJunior;
- [ ] O usuário deve visualizar depoimentos de profissionais que foram inseridos ao mercado de trabalho após participar do ecosistema SouJunior em carrossel com atraso de 5 segundos;
- [ ] Se o usuário clicar nos bullet points indicadores da quantidade de depoimentos, o depoimento referente deve aparecer deslizando em carrossel para o usuário visualizar;
- [ ] No footer deve ser padrão de acordo com o design system da SouJunior e conter o código QR code na lateral direita direcionando o candidato ao [site da SouJunior](https://www.soujunior.tech/)

**Comment by Kaleber-chaves** [comment]
Segue a documentação dos testes.

[SJV-Home Portal de vagas #355-041023-125941.pdf](https://github.com/SouJunior/products/files/12803573/SJV-Home.Portal.de.vagas.355-041023-125941.pdf)
